In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
dataset=pd.read_csv("CKD.csv")

In [3]:
dataset

,age,bp,sg,al,su,rbc,pc,pcc,ba,bgr,...,pcv,wc,rc,htn,dm,cad,appet,pe,ane,classification
0,2.000000,76.459948,c,3.0,0.0,normal,abnormal,notpresent,notpresent,148.112676,...,38.868902,8408.191126,4.705597,no,no,no,yes,yes,no,yes
1,3.000000,76.459948,c,2.0,0.0,normal,normal,notpresent,notpresent,148.112676,...,34.000000,12300.000000,4.705597,no,no,no,yes,poor,no,yes
2,4.000000,76.459948,a,1.0,0.0,normal,normal,notpresent,notpresent,99.000000,...,34.000000,8408.191126,4.705597,no,no,no,yes,poor,no,yes
3,5.000000,76.459948,d,1.0,0.0,normal,normal,notpresent,notpresent,148.112676,...,38.868902,8408.191126,4.705597,no,no,no,yes,poor,yes,yes
4,5.000000,50.000000,c,0.0,0.0,normal,normal,notpresent,notpresent,148.112676,...,36.000000,12400.000000,4.705597,no,no,no,yes,poor,no,yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
394,51.492308,70.000000,a,0.0,0.0,normal,normal,notpresent,notpresent,219.000000,...,37.000000,9800.000000,4.400000,no,no,no,yes,poor,no,yes
395,51.492308,70.000000,c,0.0,2.0,normal,normal,notpresent,notpresent,220.000000,...,27.000000,8408.191126,4.705597,yes,yes,no,yes,poor,yes,yes
396,51.492308,70.000000,c,3.0,0.0,normal,normal,notpresent,notpresent,110.000000,...,26.000000,9200.000000,3.400000,yes,yes,no,poor,poor,no,yes
397,51.492308,90.000000,a,0.0,0.0,normal,normal,notpresent,notpresent,207.000000,...,38.868902,8408.191126,4.705597,yes,yes,no,yes,poor,yes,yes
398,51.492308,80.000000,a,0.0,0.0,normal,normal,notpresent,notpresent,100.000000,...,53.000000,8500.000000,4.900000,no,no,no,yes,poor,no,no

In [4]:
dataset=pd.get_dummies(dataset,drop_first=True)

In [5]:
dataset=dataset.astype(int)

In [6]:
dataset

,age,bp,al,su,bgr,bu,sc,sod,pot,hrmo,...,pc_normal,pcc_present,ba_present,htn_yes,dm_yes,cad_yes,appet_yes,pe_yes,ane_yes,classification_yes
0,2,76,3,0,148,57,3,137,4,12,...,0,0,0,0,0,0,1,1,0,1
1,3,76,2,0,148,22,0,137,4,10,...,1,0,0,0,0,0,1,0,0,1
2,4,76,1,0,99,23,0,138,4,12,...,1,0,0,0,0,0,1,0,0,1
3,5,76,1,0,148,16,0,138,3,8,...,1,0,0,0,0,0,1,0,1,1
4,5,50,0,0,148,25,0,137,4,11,...,1,0,0,0,0,0,1,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
394,51,70,0,0,219,36,1,139,3,12,...,1,0,0,0,0,0,1,0,0,1
395,51,70,0,2,220,68,2,137,4,8,...,1,0,0,1,1,0,1,0,1,1
396,51,70,3,0,110,115,6,134,2,9,...,1,0,0,1,1,0,0,0,0,1
397,51,90,0,0,207,80,6,142,5,8,...,1,0,0,1,1,0,1,0,1,1
398,51,80,0,0,100,49,1,140,5,16,...,1,0,0,0,0,0,1,0,0,0

In [7]:
dataset.columns

Index(['age', 'bp', 'al', 'su', 'bgr', 'bu', 'sc', 'sod', 'pot', 'hrmo', 'pcv',
       'wc', 'rc', 'sg_b', 'sg_c', 'sg_d', 'sg_e', 'rbc_normal', 'pc_normal',
       'pcc_present', 'ba_present', 'htn_yes', 'dm_yes', 'cad_yes',
       'appet_yes', 'pe_yes', 'ane_yes', 'classification_yes'],
      dtype='object')

In [8]:
independent=dataset[['age', 'bp', 'al', 'su', 'bgr', 'bu', 'sc', 'sod', 'pot', 'hrmo', 'pcv',
       'wc', 'rc', 'sg_b', 'sg_c', 'sg_d', 'sg_e', 'rbc_normal', 'pc_normal',
       'pcc_present', 'ba_present', 'htn_yes', 'dm_yes', 'cad_yes',
       'appet_yes', 'pe_yes', 'ane_yes']]

In [9]:
dependent=dataset[['classification_yes']]

In [10]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(independent,dependent,test_size=0.30,random_state=0)

In [11]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
X_train=sc.fit_transform(X_train)
X_test=sc.transform(X_test)

In [12]:
from sklearn.neighbors import KNeighborsClassifier

In [13]:
from sklearn.model_selection import GridSearchCV
param_grid = {'weights':['uniform', 'distance'],'n_neighbors':[5],'p':[2],'metric':['minkowski']}
grid = GridSearchCV(KNeighborsClassifier(), param_grid, refit = True, verbose = 3,n_jobs=-1,scoring='f1_weighted')
grid.fit(X_train,y_train)

Fitting 5 folds for each of 2 candidates, totalling 10 fits

C:\Users\Rayen Subhikha\Downloads\Rayen-personal\Lib\site-packages\sklearn\neighbors\_classification.py:228: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)

GridSearchCV(estimator=KNeighborsClassifier(), n_jobs=-1,
             param_grid={'metric': ['minkowski'], 'n_neighbors': [5], 'p': [2],
                         'weights': ['uniform', 'distance']},
             scoring='f1_weighted', verbose=3)

In [14]:
re=grid.cv_results_

In [15]:
grid_predictions=grid.predict(X_test)

In [16]:
from sklearn.metrics import confusion_matrix
cm=confusion_matrix(y_test,grid_predictions)

In [17]:
from sklearn.metrics import classification_report
clf_report=classification_report(y_test,grid_predictions)

In [18]:
print(clf_report)

              precision    recall  f1-score   support

           0       0.90      1.00      0.95        45
           1       1.00      0.93      0.97        75

    accuracy                           0.96       120
   macro avg       0.95      0.97      0.96       120
weighted avg       0.96      0.96      0.96       120

In [19]:
table=pd.DataFrame.from_dict(re)

In [20]:
table

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_metric,param_n_neighbors,param_p,param_weights,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.059480,0.011214,0.188717,0.000893,minkowski,5,2,uniform,"{'metric': 'minkowski', 'n_neighbors': 5, 'p':...",0.964572,0.964572,0.929513,0.964572,0.963912,0.957428,0.01396,1
1,0.007055,0.011242,0.123011,0.065124,minkowski,5,2,distance,"{'metric': 'minkowski', 'n_neighbors': 5, 'p':...",0.964572,0.964572,0.929513,0.964572,0.963912,0.957428,0.01396,1

In [21]:
age=int(input("Age:"))
bp=float(input("bp:"))
al=int(input("al:"))
su=int(input("su:"))
bgr=float(input("bgr:"))
bu=float(input("bu:"))
sc=float(input("sc:"))
sod=float(input("sod:"))
pot=float(input("pot:"))
hrmo=float(input("hrmo:"))
pcv=float(input("pcv:"))
wc=float(input("wc:"))
rc=float(input("rc:"))
sg_b=int(input("sg_b:"))
sg_c=int(input("sg_c:"))
sg_d=int(input("sg_d:"))
sg_e=int(input("sg_e:"))
rbc_normal=int(input("rbc_normal:"))
pc_normal=int(input("pc_normal:"))
pcc_normal=int(input("pcc_normal:"))
pcc_present=int(input("pcc_present:"))
ba_present=int(input("ba_present:"))
htn_yes=int(input("htn_yes:"))
dm_yes=int(input("dm_yes:"))
cad_yes=int(input("cad_yes:"))
appet_yes=int(input("appet_yes:"))
pe_yes=int(input("pe_yes:"))
ane_yes=int(input("ane_yes:"))

Age:15
bp:76
al:0
su:0
bgr:80
bu:66
sc:0.8
sod:138
pot:3.2
hrmo:10.7
pcv:34
wc:7700
rc:5.2
sg_b:0
sg_c:0
sg_d:0
sg_e:0
rbc_normal:0
pc_normal:0
pcc_normal:0
pcc_present:0
ba_present:0
htn_yes:0
dm_yes:0
cad_yes:0
appet_yes:0
pe_yes:0
ane_yes:0

In [22]:
Future_Prediction = grid.predict([[age, bp, al, su, bgr, bu, sc, sod, pot, hrmo, pcv,
                                   wc, rc, sg_b, sg_c, sg_d, sg_e, rbc_normal,pcc_present, pc_normal,ba_present, htn_yes, dm_yes, cad_yes,
                                   appet_yes, pe_yes, ane_yes]])
print("Future_Prediction={}".format(Future_Prediction))

Future_Prediction=[1]