In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
dataset=pd.read_csv("CKD.csv")

In [3]:
dataset

,age,bp,sg,al,su,rbc,pc,pcc,ba,bgr,...,pcv,wc,rc,htn,dm,cad,appet,pe,ane,classification
0,2.000000,76.459948,c,3.0,0.0,normal,abnormal,notpresent,notpresent,148.112676,...,38.868902,8408.191126,4.705597,no,no,no,yes,yes,no,yes
1,3.000000,76.459948,c,2.0,0.0,normal,normal,notpresent,notpresent,148.112676,...,34.000000,12300.000000,4.705597,no,no,no,yes,poor,no,yes
2,4.000000,76.459948,a,1.0,0.0,normal,normal,notpresent,notpresent,99.000000,...,34.000000,8408.191126,4.705597,no,no,no,yes,poor,no,yes
3,5.000000,76.459948,d,1.0,0.0,normal,normal,notpresent,notpresent,148.112676,...,38.868902,8408.191126,4.705597,no,no,no,yes,poor,yes,yes
4,5.000000,50.000000,c,0.0,0.0,normal,normal,notpresent,notpresent,148.112676,...,36.000000,12400.000000,4.705597,no,no,no,yes,poor,no,yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
394,51.492308,70.000000,a,0.0,0.0,normal,normal,notpresent,notpresent,219.000000,...,37.000000,9800.000000,4.400000,no,no,no,yes,poor,no,yes
395,51.492308,70.000000,c,0.0,2.0,normal,normal,notpresent,notpresent,220.000000,...,27.000000,8408.191126,4.705597,yes,yes,no,yes,poor,yes,yes
396,51.492308,70.000000,c,3.0,0.0,normal,normal,notpresent,notpresent,110.000000,...,26.000000,9200.000000,3.400000,yes,yes,no,poor,poor,no,yes
397,51.492308,90.000000,a,0.0,0.0,normal,normal,notpresent,notpresent,207.000000,...,38.868902,8408.191126,4.705597,yes,yes,no,yes,poor,yes,yes
398,51.492308,80.000000,a,0.0,0.0,normal,normal,notpresent,notpresent,100.000000,...,53.000000,8500.000000,4.900000,no,no,no,yes,poor,no,no

In [4]:
dataset=pd.get_dummies(dataset,drop_first=True)

In [5]:
dataset=dataset.astype(int)

In [6]:
dataset

,age,bp,al,su,bgr,bu,sc,sod,pot,hrmo,...,pc_normal,pcc_present,ba_present,htn_yes,dm_yes,cad_yes,appet_yes,pe_yes,ane_yes,classification_yes
0,2,76,3,0,148,57,3,137,4,12,...,0,0,0,0,0,0,1,1,0,1
1,3,76,2,0,148,22,0,137,4,10,...,1,0,0,0,0,0,1,0,0,1
2,4,76,1,0,99,23,0,138,4,12,...,1,0,0,0,0,0,1,0,0,1
3,5,76,1,0,148,16,0,138,3,8,...,1,0,0,0,0,0,1,0,1,1
4,5,50,0,0,148,25,0,137,4,11,...,1,0,0,0,0,0,1,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
394,51,70,0,0,219,36,1,139,3,12,...,1,0,0,0,0,0,1,0,0,1
395,51,70,0,2,220,68,2,137,4,8,...,1,0,0,1,1,0,1,0,1,1
396,51,70,3,0,110,115,6,134,2,9,...,1,0,0,1,1,0,0,0,0,1
397,51,90,0,0,207,80,6,142,5,8,...,1,0,0,1,1,0,1,0,1,1
398,51,80,0,0,100,49,1,140,5,16,...,1,0,0,0,0,0,1,0,0,0

In [7]:
dataset.columns

Index(['age', 'bp', 'al', 'su', 'bgr', 'bu', 'sc', 'sod', 'pot', 'hrmo', 'pcv',
       'wc', 'rc', 'sg_b', 'sg_c', 'sg_d', 'sg_e', 'rbc_normal', 'pc_normal',
       'pcc_present', 'ba_present', 'htn_yes', 'dm_yes', 'cad_yes',
       'appet_yes', 'pe_yes', 'ane_yes', 'classification_yes'],
      dtype='object')

In [8]:
independent=dataset[['age', 'bp', 'al', 'su', 'bgr', 'bu', 'sc', 'sod', 'pot', 'hrmo', 'pcv',
       'wc', 'rc', 'sg_b', 'sg_c', 'sg_d', 'sg_e', 'rbc_normal', 'pc_normal',
       'pcc_present', 'ba_present', 'htn_yes', 'dm_yes', 'cad_yes',
       'appet_yes', 'pe_yes', 'ane_yes']]

In [9]:
dependent=dataset[['classification_yes']]

In [10]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(independent,dependent,test_size=0.30,random_state=0)

In [12]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
X_train=sc.fit_transform(X_train)
X_test=sc.transform(X_test)

In [15]:
from sklearn.svm import SVC

In [18]:
from sklearn.model_selection import GridSearchCV
param_grid = {'kernel':['rbf','poly','sigmoid','linear'],'C':[10,100,1000,2000,3000]}
grid = GridSearchCV(SVC(), param_grid, refit = True, verbose = 3,n_jobs=-1,scoring='f1_weighted')
grid.fit(X_train,y_train)

Fitting 5 folds for each of 20 candidates, totalling 100 fits

C:\Users\Rayen Subhikha\Downloads\Rayen-personal\Lib\site-packages\sklearn\utils\validation.py:1184: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

GridSearchCV(estimator=SVC(), n_jobs=-1,
             param_grid={'C': [10, 100, 1000, 2000, 3000],
                         'kernel': ['rbf', 'poly', 'sigmoid', 'linear']},
             scoring='f1_weighted', verbose=3)

In [19]:
re=grid.cv_results_

In [20]:
grid_predictions=grid.predict(X_test)

In [21]:
from sklearn.metrics import confusion_matrix
cm=confusion_matrix(y_test,grid_predictions)

In [22]:
from sklearn.metrics import classification_report
clf_report=classification_report(y_test,grid_predictions)

In [23]:
print(clf_report)

              precision    recall  f1-score   support

           0       0.94      1.00      0.97        45
           1       1.00      0.96      0.98        75

    accuracy                           0.97       120
   macro avg       0.97      0.98      0.97       120
weighted avg       0.98      0.97      0.98       120

In [27]:
table=pd.DataFrame.from_dict(re)

In [28]:
table

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_C,param_kernel,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.015652,0.000603,0.017611,0.004018,10,rbf,"{'C': 10, 'kernel': 'rbf'}",0.982221,1.000000,0.982051,1.000000,1.000000,0.992854,0.008752,1
1,0.013703,0.004081,0.016492,0.001555,10,poly,"{'C': 10, 'kernel': 'poly'}",1.000000,0.982051,0.964286,0.982051,0.981894,0.982056,0.011294,9
2,0.007945,0.001971,0.017867,0.002307,10,sigmoid,"{'C': 10, 'kernel': 'sigmoid'}",0.982221,1.000000,0.946663,0.964286,1.000000,0.978634,0.020755,10
3,0.006950,0.002343,0.014869,0.003495,10,linear,"{'C': 10, 'kernel': 'linear'}",0.982221,0.946663,0.982221,0.964286,0.981894,0.971457,0.014190,12
4,0.005637,0.000815,0.013636,0.002332,100,rbf,"{'C': 100, 'kernel': 'rbf'}",0.982221,1.000000,0.982051,0.982051,1.000000,0.989265,0.008766,2
5,0.003984,0.004879,0.018044,0.005085,100,poly,"{'C': 100, 'kernel': 'poly'}",0.964572,1.000000,0.982051,0.964286,0.981894,0.978561,0.013284,11
6,0.010219,0.002849,0.014066,0.001422,100,sigmoid,"{'C': 100, 'kernel': 'sigmoid'}",0.982221,0.946663,0.964572,0.964286,0.981894,0.967927,0.013237,20
7,0.006629,0.001971,0.011256,0.003198,100,linear,"{'C': 100, 'kernel': 'linear'}",0.982221,0.946663,0.982221,0.964286,0.981894,0.971457,0.014190,12
8,0.006303,0.003305,0.015081,0.002548,1000,rbf,"{'C': 1000, 'kernel': 'rbf'}",0.982221,1.000000,0.982051,0.982051,1.000000,0.989265,0.008766,2
9,0.007721,0.004043,0.013854,0.003778,1000,poly,"{'C': 1000, 'kernel': 'poly'}",0.964572,1.000000,0.964286,1.000000,0.981894,0.982150,0.015909,6
10,0.007429,0.002593,0.013059,0.002469,1000,sigmoid,"{'C': 1000, 'kernel': 'sigmoid'}",0.982221,0.946663,0.982221,0.964286,0.981894,0.971457,0.014190,12
11,0.008236,0.004137,0.012458,0.003335,1000,linear,"{'C': 1000, 'kernel': 'linear'}",0.982221,0.946663,0.982221,0.964286,0.981894,0.971457,0.014190,12
12,0.004222,0.003838,0.015862,0.002149,2000,rbf,"{'C': 2000, 'kernel': 'rbf'}",0.982221,1.000000,0.982051,0.982051,1.000000,0.989265,0.008766,2
13,0.007750,0.003172,0.014075,0.005151,2000,poly,"{'C': 2000, 'kernel': 'poly'}",0.964572,1.000000,0.964286,1.000000,0.981894,0.982150,0.015909,6
14,0.007417,0.000726,0.013893,0.000990,2000,sigmoid,"{'C': 2000, 'kernel': 'sigmoid'}",0.982221,0.946663,0.982221,0.964286,0.981894,0.971457,0.014190,12
15,0.005223,0.002028,0.013279,0.002128,2000,linear,"{'C': 2000, 'kernel': 'linear'}",0.982221,0.946663,0.982221,0.964286,0.981894,0.971457,0.014190,12
16,0.008145,0.003947,0.015671,0.003220,3000,rbf,"{'C': 3000, 'kernel': 'rbf'}",0.982221,1.000000,0.982051,0.982051,1.000000,0.989265,0.008766,2
17,0.009234,0.003615,0.014453,0.004236,3000,poly,"{'C': 3000, 'kernel': 'poly'}",0.964572,1.000000,0.964286,1.000000,0.981894,0.982150,0.015909,6
18,0.006821,0.001604,0.013645,0.001963,3000,sigmoid,"{'C': 3000, 'kernel': 'sigmoid'}",0.982221,0.946663,0.982221,0.964286,0.981894,0.971457,0.014190,12
19,0.006220,0.001471,0.009432,0.002341,3000,linear,"{'C': 3000, 'kernel': 'linear'}",0.982221,0.946663,0.982221,0.964286,0.981894,0.971457,0.014190,12